[oauth]
  [oauth.google]
    client_id = "879889726595-qimoaemgmseam4a7l7n7i3cfhbom9ivo.apps.googleusercontent.com"
    client_secret = "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"
    redirect_url = "http://localhost:8501"
    redirect_url_test = "http://localhost:8501"